### ISSUE TITLE
Is it compatible to q2a 1.7??

### ISSUE THREAD

**Issue by gurjyot** [q2amarket/q2am-simple-adverts#2]

**Comment by q2amarket** [comment]
I haven't tested it yet. It's free so you can install and test it. Let me know if you find any issue with 1.7

**Comment by gurjyot** [comment]
Thanks for your reply @q2amarket. I would have used it but I cannot install it on a live website and local host won't show Google ads. So the only way would be that you test this plugin and let us know about the compatibility... 
Thanks again... :-)

**Comment by q2amarket** [comment]
It's been tested on latest version 1.7.2 and working fine.

**Comment by gurjyot** [comment]
Thank you for confirming @q2amarket :)
