### ISSUE TITLE
Major issue with option bloat

### ISSUE THREAD

**Issue by svivian** [q2amarket/q2am-simple-adverts#3]
Hi, just came across this issue with your plugin via Jonatan [on Q2A here](http://www.question2answer.org/qa/50650/scott-these-qa_debug_performance-data-can-help).

He had over 95,000 options in his qa_options table. Turns out it's from this plugin. I think it's from this line: https://github.com/q2amarket/q2am-simple-adverts/blob/master/qa-adverts-layer.php#L104

You use `qa_request_part(0)` to check the option but that returns a number on question pages (for example `50650` on the Q2A link above). So this adds an option to the table for every single question on the site, like
q2am_98693_advert_image_url
q2am_98693_enable_adverts
q2am_98749_advert_image_url
q2am_98749_enable_adverts
...etc

Since that's part of a layer plugin, I think what you want to add there is `$this->template` which contains the type of page, for example `question` or `users`. Hope that helps :)

**Comment by q2amarket** [comment]
@svivian Thanks and appreciate for the report and possible solution. I will fix it by this weekend.

**Comment by q2amarket** [comment]
Even I couldn't reproduce the issue I have modified the code as @svivian suggested.
